# APLIKASI ALJABAR LINIER

## ALGORITMA PAGERANK
PageRank adalah algoritma yang. dibuat oleh Larry Page. Algoritma ini digunakan oleh mesin pencarian Google yang memberikan bobot numerik untuk setiap elemen dari kumpulan dokumen hyperlink seperti Word Wide Web dengan tujuan untuk mengukur hubungan kepentingan dalam kumpulan dokumen tersebut. Dalam algoritma PageRank dihasilkan matriks yang menghitung probabilitas bahwa pengguna akan berpindah dari satu halaman ke halaman lainnya.

Algoritma PageRank umumnya diterapkan pada directed graph, namun dalam kasus undirected graph algoritma pagerank juga dapat digunakan dengan memodifikasi seperti yang diterapkan pada algoritma TextRank . Pada TextRank akan dibangun sebuah graph yang berisi hubungan antar kalimat dalam dokumen. Vertex di dalam graph ini direpresentasikan sebagai unit satuan yang akan diberikan peringkat. Vertex ini memiliki similarity yang dihubungkan oleh edges. Similarity disini dapat ditentukan dengan cosine similarity di mana akan didapat kemiripan dari setiap kalimat satu sama lain. Formula untuk peringkat berbasis grafik yang memperhitungkan bobot edge saat menghitung nilai terkait sebuah vertex dalam graf dalam dapat dilihat pada persamaan

1. Prinsip Dasar: PageRank bekerja dengan asumsi bahwa tautan dari satu halaman web ke halaman web lainnya dapat dianggap sebagai “suara” untuk halaman tujuan. Semakin banyak suara (tautan) yang diterima oleh sebuah halaman, semakin tinggi peringkatnya.

2. Bobot Tautan: Tidak semua tautan dianggap sama. Tautan dari halaman yang memiliki PageRank tinggi memberikan kontribusi lebih besar dibandingkan tautan dari halaman dengan PageRank rendah. Jadi, tautan dari situs yang sudah terkenal atau sering dikunjungi akan memberikan pengaruh lebih besar.

3. Distribusi PageRank: Setiap halaman web diberikan nilai awal yang sama. PageRank dari sebuah halaman akan dibagi secara merata ke semua halaman yang ditautkan dari halaman tersebut. Kemudian, PageRank dari semua halaman akan dihitung ulang secara iteratif hingga mencapai keseimbangan (konvergen).

4. Damping Factor: Algoritma PageRank menggunakan faktor redaman (damping factor) untuk menambahkan elemen probabilistik. Faktor ini biasanya diatur sekitar 0.85, yang berarti ada 85% kemungkinan bahwa pengguna akan mengikuti tautan di halaman tersebut, dan 15% kemungkinan mereka akan langsung menuju halaman lain secara acak. Ini membantu mencegah beberapa halaman menjadi terlalu dominan dan memastikan bahwa setiap halaman memiliki kesempatan untuk mendapatkan peringkat.



## Proses iterasi

1.Inisialisasi:

Semua halaman diberikan nilai PageRank awal yang sama, misalnya 1.

2.Perbarui Nilai PageRank:

Gunakan rumus di atas untuk memperbarui nilai PageRank setiap halaman berdasarkan PageRank halaman-halaman yang menautkannya.

3.Konvergensi:

Ulangi langkah 2 sampai nilai PageRank semua halaman berubah sangat kecil atau mencapai tingkat konvergensi yang ditentukan.



## perhitungan manual

Perhitungan Manual :
Matriks $A$ dan Vektor $v 0$
Matriks $A$ :
$$
A=\left[\begin{array}{ccccc}
0 & 0 & 0 & 0 & \frac{1}{3} \\
0 & 0 & \frac{1}{2} & 1 & \frac{1}{3} \\
\frac{1}{3} & 0 & 0 & 0 & \frac{1}{3} \\
\frac{1}{3} & 0 & \frac{1}{2} & 0 & 0 \\
\frac{1}{3} & 1 & 0 & 0 & 0
\end{array}\right]
$$

Vektor awal $v 0$ :
$$
v 0=\left[\begin{array}{l}
0.2 \\
0.2 \\
0.2 \\
0.2 \\
0.2
\end{array}\right]
$$
1. Iterasi Pertama
Mengalikan $A$ dengan $v 0$ :



### implementasi manual

In [8]:
import numpy as np

In [10]:
A = np.array ([[0,0,1,1/2],[1/3,0,0,0],[1/3,1/2,0,1/2],[1/3,1/2,0,0]])
V0 = np.array ([[0.25],[0.25],[0.25],[0.25]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 = A@V7
print(V8)
V0 = np.array ([[0.3],[0.2],[0.3],[0.2]])
V1 = A@V0
print(V1)
V2 = A@V1
print(V2)
V3 = A@V2
print(V3)
V4 = A@V3
print(V4)
V5 = A@V4
print(V5)
V6 = A@V5
print(V6)
V7 = A@V6
print(V7)
V8 =A@V7
print(V8)

[[0.375     ]
 [0.08333333]
 [0.33333333]
 [0.20833333]]
[[0.4375    ]
 [0.125     ]
 [0.27083333]
 [0.16666667]]
[[0.35416667]
 [0.14583333]
 [0.29166667]
 [0.20833333]]
[[0.39583333]
 [0.11805556]
 [0.29513889]
 [0.19097222]]
[[0.390625  ]
 [0.13194444]
 [0.28645833]
 [0.19097222]]
[[0.38194444]
 [0.13020833]
 [0.29166667]
 [0.19618056]]
[[0.38975694]
 [0.12731481]
 [0.29050926]
 [0.19241898]]
[[0.38671875]
 [0.12991898]
 [0.28978588]
 [0.19357639]]
[[0.4]
 [0.1]
 [0.3]
 [0.2]]
[[0.4       ]
 [0.13333333]
 [0.28333333]
 [0.18333333]]
[[0.375     ]
 [0.13333333]
 [0.29166667]
 [0.2       ]]
[[0.39166667]
 [0.125     ]
 [0.29166667]
 [0.19166667]]
[[0.3875    ]
 [0.13055556]
 [0.28888889]
 [0.19305556]]
[[0.38541667]
 [0.12916667]
 [0.29097222]
 [0.19444444]]
[[0.38819444]
 [0.12847222]
 [0.29027778]
 [0.19305556]]
[[0.38680556]
 [0.12939815]
 [0.29016204]
 [0.19363426]]


### implementasi code

In [12]:
import numpy as np

def perkalianMatriks(A,v0):
  vbaru = A@v0
  return vbaru

def hitung(vbaru,vlama):
  temp = 0
  for i in range(len(vbaru)):
    temp += (vbaru[i] - vlama[i])**2
  return temp

def converge(A,v0,toleransi):
  count = 1
  vbaru = perkalianMatriks(A,v0)
  iterasi = hitung(vbaru,v0)
  print(f'v{count} = {vbaru}')
  print(f'iterasi ke-{count} = {iterasi}')
  print()
  while iterasi > toleransi :
    vbaru2 = perkalianMatriks(A,vbaru)
    iterasi = hitung(vbaru2,vbaru)
    print(f'v{count+1} = {vbaru}')
    print(f'iterasi ke-{count+1} = {iterasi}')
    print()
    vbaru = vbaru2
    count += 1
  return f'urutan = {pageRank(vbaru2)}'

def pageRank(vbaru):
  return np.argsort(vbaru,axis=0)[::-1]

A = np.array([[0,0,0,0,1/3],[0,0,1/2,1,1/3],[1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
v0 = np.array([[0.2],[0.2],[0.2],[0.2],[0.2]])
toleransi = 0.01
hasil = converge(A,v0,toleransi)
print(hasil)

v1 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-1 = [0.05555556]

v2 = [[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]
iterasi ke-2 = [0.02395062]

v3 = [[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]
iterasi ke-3 = [0.00768176]

urutan = [[4]
 [1]
 [2]
 [0]
 [3]]
