# Determinan Matriks

Determinan merupakan

Sifat sifat determinan matriks :

1. Determinan dari matriks identitas adalah 1
2. Misal Determinan AB merupakan matriks bujur sangkar maka determinan matriks A dapat dikalikan dengan determinan matriks B
3. MEnukar baris dari matriks bisa merubah tanda dari determinan
4. jika matriks a dikalikan dengan skalar ,maka determinan dari ka bisa di cari dengan cara skalar dikalikan dengan orde dari matriks a,lalu dikalikan dengan determinan a.
5. melakukan operasi baris elementer tidak merupah nilai determinan dari matriks tersebut
6. Determinan matriks a tranpose sama dengan determinan matriks a.
7. Jika skalar dikalikan dengan baris 1 dari matriks pertama maka ,determinan ka bisa dicari dengan skalar dikali determinan martriks.
8. determinan matriks segitiga dicari dengan mengalikan setiap elemen yang ada di matriks diagonalnya saja

determinan adalah kumpulan skalar dari semua matrix

In [ ]:
import numpy as np
a= np.array([[2,3],[3,4]])
print ('matrix 2x2')
print (a)
b=np.array([[4,5,6],[2,3,4],[3,4,2]])
print ('matrix 3x3')
print(b)
c=np.array([[1,0],[0,1]])
print('matrix identitas 2x2')
print (c)
d=np.array([[1,0,0],[0,1,0],[0,0,1]])
print ('matrix identitas 3x3')
print (d)



matrix 2x2
[[2 3]
 [3 4]]
matrix 3x3
[[4 5 6]
 [2 3 4]
 [3 4 2]]
matrix identitas 2x2
[[1 0]
 [0 1]]
matrix identitas 3x3
[[1 0 0]
 [0 1 0]
 [0 0 1]]


1. sifat sifat determinan

In [ ]:
Ic = np.linalg.det(c)
Id = np.linalg.det(d)
print (Ic)
print (Id)

1.0
1.0


In [ ]:
inversA = np.linalg.inv(a)
print ('invers A')
print (inversA)

invers A
[[-4.  3.]
 [ 3. -2.]]


In [ ]:
inversB = np.linalg.inv(b)
print ('invers B')
print (inversB)

invers B
[[ 1.66666667 -2.33333333 -0.33333333]
 [-1.33333333  1.66666667  0.66666667]
 [ 0.16666667  0.16666667 -0.33333333]]


2. determinan dari matrix A B = Matrix identitas

In [ ]:
a1 =  np.linalg.det(a)
DetA= np.linalg.det(inversA)

kali =a1 * DetA
print (kali)


1.0


3. Determinan dari (a invers) =1/a

In [ ]:
import numpy as np
e = np.array ([[1,2,3],[2,3,4],[2,3,5]])
print ('matrix e 3x3')
print (e)
f = np.array ([[1,2,1],[2,1,2],[1,1,2]])
print ('matrix f 3x3')
print (f)
g =e@f
detg= np.linalg.det(g)
print ('matrix g')
print (g)
print ('determinan matrix g')
print (detg)

detEF =np.linalg.det(e)*np.linalg.det(f)
print ('determinan matrix f')
print (f)


matrix e 3x3
[[1 2 3]
 [2 3 4]
 [2 3 5]]
matrix f 3x3
[[1 2 1]
 [2 1 2]
 [1 1 2]]
matrix g
[[ 8  7 11]
 [12 11 16]
 [13 12 18]]
determinan matrix g
3.00000000000001
determinan matrix f
[[1 2 1]
 [2 1 2]
 [1 1 2]]


In [ ]:
matrixA = np.array ([[1,4,2],[1,1,1],[3,2,1]])
# menukarkan baris pada suatu matrix akan merubah tanda dari determinan
matrixA1= np.array ([[1,1,1],[1,4,2],[3,2,1]])

matrixA2 = np.array([[4,1,2],[1,1,1],[2,3,1]])

detA = np.linalg.det(matrixA)
detA1 = np.linalg.det (matrixA1)
detA2 =np.linalg.det (matrixA2)

print (matrixA)
print ()
print (detA.round())
print (detA1.round())
print (detA2.round())



[[1 4 2]
 [1 1 1]
 [3 2 1]]

5.0
-5.0
-5.0


4. jika baris dari matrix merupakan kelipatan dari baris atau kolom yang lain maka akan menghasilkan nol

In [ ]:
import numpy as np
matrixB = np.array([[1,4,2],[2,8,4],[3,2,1]])
matrixB1 = np.array ([[1,4,2],[2,8,3],[1,4,1]])

detB = np.linalg.det(matrixB)
detB1 = np.linal.det (matrixB1)

print (matrixB)
print (detB)
print ()
print (matrixB1)
print (detB1)

## tugas mencari determinan matriks 4x4 dengan cara ekspansi kofaktor
1. contoh matrix 4x4 :

$\begin{matrix}
A = \begin{bmatrix}
    4 & 5 & 6 & 7\\
    2 & 2 & 2 & 2\\
    4 & 3 & 2 & 3\\
    3 & 3 & 6 & 3
  \end{bmatrix}
\end{matrix}
$

2. selanjutnya tulis rumus determinan disini, mengambil baris ke-2 :

$ det(A) = a_{21} c_{21} + a_{22} c_{22}  + a_{23} c_{23} + a_{24} c_{24} $

3.selanjutnya tentukan kofaktor nya disini dari matriks A


$c_{21} = (-1)^{2+1} det(M_{21})$  
$c_{22} = (-1)^{2+2} det(M_{22})$  
$c_{23} = (-1)^{2+3} det(M_{23})$  
$c_{24} = (-1)^{2+4} det(M_{24})$

4. setelah itu kita akan cari satu-persatu determinan minor tersebut dari matriks A

5. pertama : $M_{21}$

$\begin{matrix}
  det(M21) = \begin{bmatrix}
    5 & 6 & 7 \\
    3 & 2 & 3 \\
    3 & 6 & 3
  \end{bmatrix}
\end{matrix}
$  

selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$   

selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$

$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    4 & 5 \\
    5 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 6.7 - 6.3 = 42 - 18 = -24$

hasil
$c_{21} = -1*-24$

* $c_{22} = (-1)^{2+2}det(KM22)$


$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    5 & 3 \\
    3 & 7
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 5.7 - 3.3 = 35 - 9 = 26$  

hasil
$c_{22} = -1*26$  

* $c_{23} = (-1)^{2+3}det(KM23)$  

$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    5 & 6 \\
    3 & 6
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 5.6 - 6.3 = 30 - 18 = 12$  


hasil
$c_{23} = -1*12$  


**hasil akhir dari $M_{21}$**  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M21) = 2.(-1).(-9) + 2.1.2 + 2.(-1).7$  
$det(M21) = 18 + 4 - 14 = 8$










In [1]:
import numpy as np
M21 = np.array([[3,4,5], [2,2,2], [2,5,4]])
detM21 = np.linalg.det(M21)
print(round(detM21))

8


6. **kedua : $M_{22}$**


$\begin{matrix}
  det(M22) = \begin{bmatrix}
    4 & 6 & 7 \\
    4 & 2 & 3 \\
    3 & 3 & 3
  \end{bmatrix}
\end{matrix}
$  

selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$

selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$   


$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    4 & 5 \\
    5 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 4.4 - 5.5 = 16 - 25 = -9$  


hasil
$c_{21} = -1*-9$  

* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    2 & 5 \\
    3 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 2.4 - 3.5 = 8 - 15 = -7$  


hasil
$c_{22} = -1*-7$  

* $c_{23} = (-1)^{2+3}det(KM23)$  

$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    2 & 4 \\
    3 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 2.5 - 3.4 = 10 - 12 = -2$  


hasil
$c_{23} = -1*-2$

**hasil akhir dari $M_{22}$**  
$det(M22) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M22) = 3.(-1).(-9) + 2.1.(-7) + 2.(-1).(-2)$  
$det(M22) = 27 - 14 + 4 = 17$  







In [2]:
import numpy as np
M22 = np.array([[2,4,5], [3,2,2], [3,5,4]])
detM22 = np.linalg.det(M22)
print(round(detM22))

17


ketiga : $M_{23}$

$\begin{matrix}
  det(M23) = \begin{bmatrix}
    3 & 3 & 6 \\
    2 & 2 & 2 \\
    4 & 5 & 6
  \end{bmatrix}
\end{matrix}
$  

selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$

selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$  


$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    2 & 5 \\
    2 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 2.4 - 2.5 = 8 - 10 = -2$  


hasil
$c_{21} = -1*-2$

* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    3 & 5 \\
    3 & 4
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 3.4 - 3.5 = 12 - 15 = -3$  


hasil
$c_{22} = -1*-3$  

* $c_{23} = (-1)^{2+3}det(KM23)$  

$
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    3 & 2 \\
    3 & 2
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 3.2 - 3.2 = 6 - 6 = 0$  


hasil
$c_{23} = -1*-0$

**hasil akhir dari $M_{23}$**  
$det(M23) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M23) = 3.1.(-2) + 2.(-1).(-3) + 2.1.0$  
$det(M23) = -6 + 6 = 0$  


In [3]:
import numpy as np
M23 = np.array([[3,2,5], [3,2,2], [3,2,4]])
detM23 = np.linalg.det(M23)
print(round(detM23))

0


keempat : $M_{24}$


$\begin{matrix}
  det(M24) = \begin{bmatrix}
    4 & 5 & 6 \\
    4 & 3 & 2 \\
    3 & 3 & 6
  \end{bmatrix}
\end{matrix}
$  

selanjutnya tulis rumus determinan, dan mengambil baris ke-2  
$det(M21) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$

selanjutnya tentukan kofaktor dari matriks yang $M_{21}, M_{22}, M_{23}$  
* $c_{21} = (-1)^{2 + 1} det(KM21)$  


$
\begin{matrix}
  det(KM21) = \begin{bmatrix}
    3 & 4 \\
    2 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM21) = 3.5- 2.4 = 15 - 8 = 7$  


hasil
$c_{21} = -1*7$  


* $c_{22} = (-1)^{2+2}det(KM22)$   

$
\begin{matrix}
  det(KM22) = \begin{bmatrix}
    2 & 4 \\
    3 & 5
  \end{bmatrix}
\end{matrix}
$  
$det(KM22) = 2.5 - 3.4 = 10 - 12 = -2$  


hasil
$c_{22} = -1*-2$  

 $c_{23} = (-1)^{2+3}det(KM23)$  

 $
\begin{matrix}
  det(KM23) = \begin{bmatrix}
    2 & 3 \\
    3 & 2
  \end{bmatrix}
\end{matrix}
$  
$det(KM23) = 2.2 - 3.3 = 4 - 9 = -5$  


hasil
$c_{23} = -1*-5$


**hasil akhir dari $M_{24}$**  
$det(M24) = a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23}$  
$det(M24) = 3.(-1).7 + 2.1.(-2) + 2.(-1).(-5)$  
$det(M24) = -21 - 4 + 10 = -15$






In [4]:
import numpy as np
M23 = np.array([[2,3,4], [3,2,2], [3,2,5]])
detM23 = np.linalg.det(M23)
print(round(detM23))

-15


**9. **langkah terakhir mencari determinan A****  


$det(M_{21}) = 8$  
$det(M_{22}) = 17$  
$det(M_{23}) = 0$  
$det(M_{24}) = -15$  

selanjutnya subtitusi nilai determinan dari matriks minornya  

$c_{21} = (-1)^{2+1}det(M_{21}) = -1.8$  
$c_{22} = (-1)^{2+1}det(M_{22}) = 1.17$  
$c_{23} = (-1)^{2+1}det(M_{23}) = -1.0$  
$c_{24} = (-1)^{2+1}det(M_{24}) = -1.-15$  

$a_{21}c_{21} + a_{22}c_{22} + a_{23}c_{23} + a_{24}c_{24} =$
$1.(-1).8 + 1.1.17 + 1.(-1).0 + 1.(-1).(-15) =$
$-8 + 17 + 0 + 15 = 4$  



In [5]:
import numpy as np
A = np.array([[2,3,4,5], [1,1,1,1], [3,2,2,2], [3,2,5,4]])
detA = np.linalg.det(A)
print("A: \n", A)
print()
print("Determinan A = ", round(detA))

A: 
 [[2 3 4 5]
 [1 1 1 1]
 [3 2 2 2]
 [3 2 5 4]]

Determinan A =  4
