# konsep eigenvalue dan eigen vektor
Misalkan A adalah matrik bujur sangkar dengan derat n. JIka terdapat
vektor tidak nol x dan skalar λ sehingga,
Ax = λx
maka λ disebut eigenvalue dari A, dan x disebut eigenvector, yang nilainya
bersesuai dengan eigenvalue λ.

Ax = λx

Ax: vektor x setelah transformasi linier.
λx: perkalian bilangan riel dari x, i.e. peregangan dari vektor x.
Transformasi linier untuk eigenvector menghasilkan peregangan vektor
sebanyak eigenvalue kali.

Note : Vektor nol tidak bisa menjadi vektor eigen meskipun A0 = λ0, namun
λ = 0 bisa menjadi nilai eigen.




## Menghitung Eigenvalues dan Eigenvectors

Sedikit perubahan definisinya, atau dengan menggunakan transformasi
linier untuk memahami: transformasi linier A untuk vektor eigen x setara
dengan transformasi linier peregangan λI.

Ax = λI x

Dua transformasi linier untuk vektor x ekuivalen,

(A − λI) x = 0.

Oleh karena itu, vektor x berada di ruang nol matriks (A − λI). Untuk
membuat persamaan linier ini memiliki solusi bukan nol (yaitu membuat
dimensi ruang nol bukan nol), matriks (A − λI) tidak boleh berupa
matriks rank penuh (full rank) Dinyatakan dalam bentuk determinan:
det (A − λI) = 0


## Mencari nilai eigen value dan eigen vector pada matriks 2x2 menggunakan numpy











In [1]:
import numpy as np
from numpy.linalg import eig

# Matriks 2x2
A = np.array([[1,4],[2,3]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w, '\n')
print('E-value', v.round(), '\n')

[[1 4]
 [2 3]] 

E-value [-1.  5.] 

E-value [[-1. -1.]
 [ 0. -1.]] 



## Mencari nilai eigen value dan eigen vector pada matriks 3x3 menggunakan numpy



In [2]:
import numpy as np
from numpy.linalg import eig

# Matriks 3x3
A = np.array([[1,4,1],[2,3,2],[2,4,5]])

# Menghitung eigenvalue dan eigenvector
w,v = eig(A)

print(A, '\n')
print('E-value', w.round(), '\n')
print('E-value', v.round(), '\n')

[[1 4 1]
 [2 3 2]
 [2 4 5]] 

E-value [ 8. -1.  2.] 

E-value [[-0. -1. -1.]
 [-0.  0. -0.]
 [-1.  0.  1.]] 



## Contoh Implementasi Eigenvalue dan Eigenvector





In [3]:
import numpy as np

def pcaEVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)
    C = (X_centered.T @ X_centered) / (n - 1)
    e_vals, e_vecs = np.linalg.eig(C)

    idx = e_vals.argsort()[::-1]
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]

    return (X_centered @ e_vecs), e_vals, e_vecs

X = np.array([[3, 2],
              [2, 3]])

components, eigenvalues, eigenvectors = pcaEVD(X)

rounded_components = np.round(components)
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)
print("Eigenvectors:\n", rounded_eigenvectors)

Components:
 [[ 1. -0.]
 [-1.  0.]]
Eigenvalues:
 [1. 0.]
Eigenvectors:
 [[ 1.  1.]
 [-1.  1.]]
